# Generated by Django 5.2.7 on 2025-10-19 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Eleição')),
                ('tipo', models.CharField(choices=[('PRESIDENCIAL', 'Presidente, Governador e Senador'), ('MUNICIPAL', 'Prefeito e Vereador')], max_length=20, verbose_name='Tipo de Eleição')),
                ('status', models.CharField(choices=[('NAO_INICIADA', 'Não Iniciada'), ('EM_ANDAMENTO', 'Em Andamento'), ('FINALIZADA', 'Finalizada')], default='NAO_INICIADA', max_length=20, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Eleitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(help_text='Ex: CPF ou Título de Eleitor', max_length=50, unique=True)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('digitos', models.PositiveSmallIntegerField(default=2, help_text='Número de dígitos do cargo, ex: 2 para prefeito, 3 para deputado')),
                ('eleicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='urna.eleicao')),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(verbose_name='Número do Candidato')),
                ('partido', models.CharField(max_length=100)),
                ('foto', models.ImageField(help_text='Foto do candidato', upload_to='fotos_candidatos/')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='urna.cargo')),
                ('eleitor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidato', to='urna.eleitor')),
            ],
            options={
                'unique_together': {('cargo', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_voto', models.CharField(choices=[('VALIDO', 'Válido'), ('BRANCO', 'Branco'), ('NULO', 'Nulo')], max_length=10)),
                ('data_voto', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canditato', to='urna.candidato')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='urna.cargo')),
                ('eleicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='urna.eleicao')),
                ('eleitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urna.eleitor')),
            ],
            options={
                'unique_together': {('eleitor', 'eleicao', 'cargo')},
            },
        ),
    ]
