# Generated by Django 5.2.7 on 2025-10-23 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleicao',
            name='data_finalizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voto',
            name='candidato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votos', to='urna.candidato'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='tipo_voto',
            field=models.CharField(choices=[('VALIDO', 'Válido'), ('BRANCO', 'Branco'), ('NULO', 'Nulo')], editable=False, max_length=10),
        ),
    ]
