# Generated by Django 5.2.7 on 2025-10-23 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urna', '0002_eleicao_data_finalizacao_alter_voto_candidato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='eleitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidato', to='urna.eleitor'),
        ),
    ]
