# Generated by Django 5.2.7 on 2025-10-23 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urna', '0003_alter_candidato_eleitor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleitor',
            name='nome',
        ),
        migrations.AddField(
            model_name='eleitor',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='eleitor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
